<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Pseudo-absence and background data</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="site_libs/anchor-sections-1.0/anchor-sections.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Species distribution modelling</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="schedule.html">Course schedule</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    R practicals
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="0_Intro.html">0. Introduction to R</a>
    </li>
    <li>
      <a href="1_SpeciesData.html">1. Species data</a>
    </li>
    <li>
      <a href="2_EnvData.html">2. Environmental data</a>
    </li>
    <li>
      <a href="3_SDM_intro.html">3. SDMs: simple model fitting</a>
    </li>
    <li>
      <a href="4_SDM_eval.html">4. SDMs: assessment and prediction</a>
    </li>
    <li>
      <a href="5_pseudoabsence.html">5. Pseudo-absence and background data</a>
    </li>
    <li>
      <a href="6_SDM_algorithms.html">6. SDMs: algorithms</a>
    </li>
    <li>
      <a href="7_SDM_ensembles.html">7. SDMs: ensembles</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://damariszurell.github.io">
    <span class="fa fa-home"></span>
     
  </a>
</li>
<li>
  <a href="https://twitter.com/ZurellLab">
    <span class="fa fa-twitter"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Pseudo-absence and background data</h1>

</div>


<div class="alert alert-info">
<p><strong>RStudio project</strong></p>
<p>Open the RStudio project that we created in the first session. I recommend to use this RStudio project for the entire course and within the RStudio project create separate R scripts for each session.</p>
<ul>
<li>Create a new empty R script by going to the tab “File”, select “New File” and then “R script”</li>
<li>In the new R script, type <code># Session 5: Pseudo-absence and background data</code> and save the file in your folder “scripts” within your project folder, e.g. as “5_PseudoAbsences.R”</li>
</ul>
</div>
<div id="introduction" class="section level1">
<h1><span class="header-section-number">1</span> Introduction</h1>
<p>In the previous sessions, we have worked with very convenient presence/absence data to train our species distribution models (SDMs). However, as you have seen when downloading your own GBIF data, we often have only presence records available. Absence data are also inherently difficult to get because it requires a very high sampling effort to classify a species as absent from a location. For plants, we would need complete inventories of a larger region, e.g. several 100 m plots placed within larger 1 km sample squares. For birds, we would need several visits to a specific region within the breeding season. In both cases, we could still miss some species, meaning that we do not record the species although present (resulting in a false negative).</p>
<p>But what should we do if absence data are not available? Most SDM algorithms (except the profile methods, see session 6) need some kind of absence or background data to contrast the presence data to. There are different approaches for creating background data or pseudo-absence data <span class="citation">(Barbet-Massin et al. 2012; Kramer-Schadt et al. 2013; Phillips et al. 2009)</span>, although there is still room for further developments in this field and more clear-cut recommendations for users would be certainly useful. Nevertheless, I hope this tutorial will provide some examples of how to deal with presence-only data. For advice on how many background/pseudo-absence points you need, please read <span class="citation">(Barbet-Massin et al. 2012)</span>.</p>
<p>In this session, we look at four different ways of creating background/pseudo-absence data:</p>
<ul>
<li>random selection of points within study area (including or excluding the presence locations) <span class="citation">(Barbet-Massin et al. 2012)</span></li>
<li>random selection of points outside of study area <span class="citation">(Barbet-Massin et al. 2012)</span></li>
<li>accounting for spatial sampling bias using target-group selection <span class="citation">(Phillips et al. 2009)</span></li>
<li>accounting for spatial sampling bias using inverse distance weighting <span class="citation">(Kramer-Schadt et al. 2013)</span></li>
</ul>
</div>
<div id="species-presence-data" class="section level1">
<h1><span class="header-section-number">2</span> Species presence data</h1>
<p>I created a virtual species data set with presence points for a dummy species called <em>Populus imagines</em> and sister species <em>Populus spp</em>. The spatial resolution of the data is 5 minutes. You can download the data <a href="data/Prac5_data.zip">here</a> or from the moodle page.</p>
<p>Load and plot the data:</p>
<pre class="r"><code>library(raster)
library(dismo)

mask &lt;- raster(&#39;data/Prac5_Europe5min.grd&#39;)
sp &lt;- read.table(&#39;data/Prac5_presences.txt&#39;, header=T)

# Plot the map and data
plot(mask,col=&#39;grey&#39;,legend=F)
points(sp[sp$sp==&#39;Populus_imagines&#39;,1:2],pch=&#39;+&#39;,col=&#39;red&#39;)
points(sp[sp$sp==&#39;Populus_spp&#39;,1:2],pch=&#39;+&#39;,cex=0.3,col=&#39;grey20&#39;)</code></pre>
<p><img src="5_pseudoabsence_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
</div>
<div id="backgroundpseudo-absence-data-selection" class="section level1">
<h1><span class="header-section-number">3</span> Background/Pseudo-absence data selection</h1>
<p>We use a lot of methods from the <code>dismo</code> tutorials, which are worth looking into (<a href="https://rspatial.org/raster/sdm/3_sdm_absence-background.html">see link here</a>).</p>
<div id="random-selection-of-points-within-study-area-but-excluding-the-presence-location" class="section level2">
<h2><span class="header-section-number">3.1</span> Random selection of points within study area but excluding the presence location</h2>
<p>The <code>dismo</code> package has a function to sample random points (background data).</p>
<pre class="r"><code># Randomly select background points from study region
bg_rand &lt;- randomPoints(mask, 500)

# Plot the map and data
plot(mask,col=&#39;grey&#39;,legend=F)
points(sp[sp$sp==&#39;Populus_imagines&#39;,1:2],pch=&#39;+&#39;,col=&#39;red&#39;)
points(bg_rand,pch=19,cex=0.3)</code></pre>
<p><img src="5_pseudoabsence_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>So, this function will by default sample from the entire study area independent of the presence points. We can also provide the presence points as additional argument, and by that make sure that random background data are not sampled from presence locations.</p>
<pre class="r"><code># Randomly select background data but excluding presence locations
bg_rand2 &lt;- randomPoints(mask, 500, p=sp[sp$sp==&#39;Populus_imagines&#39;,1:2])

# Plot the map and data
plot(mask,col=&#39;grey&#39;,legend=F)
points(sp[sp$sp==&#39;Populus_imagines&#39;,1:2],pch=&#39;+&#39;,col=&#39;red&#39;)
points(bg_rand2,pch=19,cex=0.3)</code></pre>
<p><img src="5_pseudoabsence_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>Also, we can define an extent from where random points should be drawn. By default, this extent is increased by 5% at each side. To circumvent this, we set <code>extf=1.0</code>.</p>
<pre class="r"><code># Define extent object:
e &lt;- extent(8,24,46,57)

# Randomly select background data within a restricted extent
bg_rand3 &lt;- randomPoints(mask, 500, p=sp[sp$sp==&#39;Populus_imagines&#39;,1:2], ext=e, extf=1.0)

# Plot the map and data
plot(mask,col=&#39;grey&#39;,legend=F)
points(sp[sp$sp==&#39;Populus_imagines&#39;,1:2],pch=&#39;+&#39;,col=&#39;red&#39;)
points(bg_rand3,pch=19,cex=0.3)
plot(e, add=TRUE, col=&#39;red&#39;)</code></pre>
<p><img src="5_pseudoabsence_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>Last, we could also restrict the random samples to within a certain buffer distance. For this, we first create a <code>SpatialPointsDataFrame</code>, then place a buffer around these and sample from within the buffer.</p>
<pre class="r"><code># Make SpatialPointsDataFrame:
pop_imag &lt;- sp[sp$sp==&#39;Populus_imagines&#39;,1:2]
coordinates(pop_imag) &lt;- ~x+y
projection(pop_imag) &lt;- CRS(&#39;+proj=longlat +datum=WGS84&#39;)

# Then, place a buffer of 200 km radius around our presence points
x &lt;- buffer(pop_imag,width=200000)

# Set all raster cells outside the buffer to NA
x &lt;- mask(mask,x)

# Randomly select background data within the buffer
bg_rand4 &lt;- randomPoints(x, 500)

# Plot the map and data
plot(mask,col=&#39;grey&#39;,legend=F)
plot(x, legend=F, add=T)
points(sp[sp$sp==&#39;Populus_imagines&#39;,1:2],pch=&#39;+&#39;,col=&#39;red&#39;)
points(bg_rand4,pch=19,cex=0.3)</code></pre>
<p><img src="5_pseudoabsence_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
</div>
<div id="random-selection-of-points-outside-of-study-area" class="section level2">
<h2><span class="header-section-number">3.2</span> Random selection of points outside of study area</h2>
<p><span class="citation">Barbet-Massin et al. (2012)</span> also suggested a method to sample pseudo-absences only beyond a minimum distance from the presence points. We can also use the buffering approach from above to achieve this.</p>
<pre class="r"><code># Place a buffer of 100 km radius around our presence points
x &lt;- buffer(pop_imag,width=200000)

# Set all raster cells outside the buffer to NA
x &lt;- mask(mask,x)

# Now, we set all the buffer cells in the mask to NA
mask2 &lt;- mask
values(mask2)[values(x)==1 &amp; !is.na(values(x))] &lt;- NA

# Randomly select background data outside the buffer
bg_far &lt;- randomPoints(mask2, 500)

# Plot the map and data
plot(mask,col=&#39;grey&#39;,legend=F)
plot(x,legend=F, add=T)
points(sp[sp$sp==&#39;Populus_imagines&#39;,1:2],pch=&#39;+&#39;,col=&#39;red&#39;)
points(bg_far,pch=19,cex=0.3)</code></pre>
<p><img src="5_pseudoabsence_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
</div>
<div id="accounting-for-spatial-sampling-bias-using-target-group-selection" class="section level2">
<h2><span class="header-section-number">3.3</span> Accounting for spatial sampling bias using target-group selection</h2>
<p>A critical assumption behind the above-mentioned background/pseudo-absence sampling is that the presence points were systematically or randomly sampled from the known distribution and are not spatially biased. In practice, this assumption is often violated, for example when observers go to more easily accessible areas. <span class="citation">Phillips et al. (2009)</span> suggested a target-group sampling for this. The idea is that we use the presence points of other groups of species as potential pseudo-absence points to mimic survey effort. These target groups should be collected or observed using the same methods and equipments. So, this approach is kind of assuming that no complete inventories were made by the observers but that there is a chance that if the species had been there it would have been observed along with the others.</p>
<p>Here, we use the sister populus species as target group.</p>
<pre class="r"><code># Randomly select background points from the target group
p &lt;- sample(seq_len(nrow(sp[sp$sp==&#39;Populus_spp&#39;,])), 500)
bg_target &lt;- sp[sp$sp==&#39;Populus_spp&#39;,1:2][p,]

# Plot the map and data
plot(mask,col=&#39;grey&#39;,legend=F)
points(sp[sp$sp==&#39;Populus_imagines&#39;,1:2],pch=&#39;+&#39;,col=&#39;red&#39;)
points(bg_target,pch=19,cex=0.3)</code></pre>
<p><img src="5_pseudoabsence_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
</div>
<div id="accounting-for-spatial-sampling-bias-using-inverse-distance-weighting" class="section level2">
<h2><span class="header-section-number">3.4</span> Accounting for spatial sampling bias using inverse distance weighting</h2>
<p>In the last example, we manipulate the background to have the same sampling bias as the presence data <span class="citation">(Kramer-Schadt et al. 2013)</span>. For example, this is particularly useful if presence records are restricted to easily accessible areas like roads. We use inverse distance weighting to define the sampling density of the presence points and then sample background proportional to that density. Following <span class="citation">Kramer-Schadt et al. (2013)</span>, we assume a low sampling effort outside the sampling range of the presence data - here a 5% sampling effort.</p>
<pre class="r"><code># Compute inverse distance weighted interpolation and create raster with density layer
idw &lt;- geoIDW(as.matrix(sp[sp$sp==&#39;Populus_imagines&#39;,1:2]), 
              randomPoints(mask, sum(sp$sp==&#39;Populus_imagines&#39;)))
idw_r &lt;- predict(mask, idw)</code></pre>
<pre><code>## [inverse distance weighted interpolation]</code></pre>
<pre class="r"><code># Re-classify density values below 0.05 indicating a 1/20 of the sampling effort
values(idw_r)[values(idw_r) &lt; 0.05] &lt;- 0.05

# Clip to land mass
idw_r &lt;- mask(idw_r,mask)

# Randomly select background data proportional to sampling density in presence data
bg_idw &lt;- randomPoints(idw_r, 500, prob=T)

# Plot the map and data
plot(idw_r)
points(sp[sp$sp==&#39;Populus_imagines&#39;,1:2],pch=&#39;+&#39;,col=&#39;red&#39;)
points(bg_idw,pch=19,cex=0.3)</code></pre>
<p><img src="5_pseudoabsence_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
</div>
</div>
<div id="workflow-for-joining-presence-and-backgroundpseudo-absence-data" class="section level1">
<h1><span class="header-section-number">4</span> Workflow for joining presence and background/pseudo-absence data</h1>
<p>In session 2, we have already learned how to join species data and environmental data (at 10 min resolution) using the Alpine Shrew as example species. Here, we will revisit this example, sample random background data and join these with environmental data to come up with a dataset containing presences and background data as well as the climatic predictors.</p>
<pre class="r"><code># Load the species presence data (here, the data set from session 1):
load(&#39;data/gbif_shrew.RData&#39;)

head(gbif_shrew[,1:4])</code></pre>
<pre><code>##          key             scientificName decimalLatitude decimalLongitude
## 1 2873903585 Sorex alpinus Schinz, 1837        46.03147        11.579116
## 2 2251919320 Sorex alpinus Schinz, 1837        47.69411        13.681602
## 3 2330155268 Sorex alpinus Schinz, 1837        48.12057         8.109648
## 4 2843496135 Sorex alpinus Schinz, 1837        47.65534        13.148056
## 5 3010682738 Sorex alpinus Schinz, 1837        47.66000        13.150000
## 6 2269283117 Sorex alpinus Schinz, 1837        46.39159        10.421819</code></pre>
<pre class="r"><code># Plot the species presences
library(maptools)
data(wrld_simpl)

plot(wrld_simpl,xlim=c(-12,45), ylim=c(35,73))
points(gbif_shrew$decimalLongitude, gbif_shrew$decimalLatitude, col=&#39;red&#39;,  pch=19)</code></pre>
<p><img src="5_pseudoabsence_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>You have already downloaded the climate data in session 2 and can simply read it back in. We crop it to European extent.</p>
<pre class="r"><code># You may have to adjust the path to your folder structure:
clim &lt;- getData(&quot;worldclim&quot;, var=&quot;bio&quot;, res=10, download=F, path=&quot;data/clim_data&quot;)

# Crop to Europe
clim &lt;- crop(clim, c(-12,45,35,73))</code></pre>
<p>What is important to consider is that you kind of arbitrarily chose a scale of analysis by chosing climate data (or other environmental data) at a certain spatial resolution. Here, we chose a spatial resolution of 10 minutes while the species data may actually be at a finer resolution. So, we first make sure that our species data are fit to the spatial resolution, meaning we remove any duplicates within 10 minute cells. We do this by joining the species data with the environmental data (basically, repeating what we had already done at the end of session 2). Then, we can remove the duplicate cells.</p>
<pre class="r"><code># Extract environmental data and raster cellnumbers for the species data
gbif_shrew2 &lt;- cbind(gbif_shrew[,c(&#39;decimalLongitude&#39;,&#39;decimalLatitude&#39;)], raster::extract(x = clim[[1]], 
    y = data.frame(gbif_shrew[,c(&#39;decimalLongitude&#39;,&#39;decimalLatitude&#39;)]), cellnumbers=T ))

# Now we remove the rows with duplicate cellnumbers:
gbif_shrew2 &lt;- gbif_shrew2[!duplicated(gbif_shrew2$cells),]

# Actually, we just need the new coordinates:
gbif_shrew2 &lt;- gbif_shrew2[,c(&#39;decimalLongitude&#39;,&#39;decimalLatitude&#39;)]</code></pre>
<p>We place a buffer of 200 km around the shrew records and sample background points randomly from within the buffer but excluding presence locations (please think about it for a moment whether a different pseudo-absence/background data strategy would be more appropriate for you).</p>
<pre class="r"><code># Make SpatialPointsDataFrame:
presences &lt;- gbif_shrew2
coordinates(presences) &lt;- ~decimalLongitude + decimalLatitude
projection(presences) &lt;- CRS(&#39;+proj=longlat +datum=WGS84&#39;)

# Then, place a buffer of 200 km radius around our presence points
buf &lt;- buffer(presences,width=200000)

# Create a mask with target resolution and extent from climate layers
mask &lt;- clim[[1]]
values(mask)[!is.na(values(mask))] &lt;- 1
plot(mask, col=&#39;grey90&#39;, legend=F)

# Set all raster cells outside the buffer to NA.
buf &lt;- mask(mask,buf)
plot(buf, add=T, col=&#39;grey60&#39;, legend=F)

# Randomly select background data within the buffer, excluding presence locations. We sample 10 times as many background data as we have presences.
bg_dat &lt;- randomPoints(buf, length(presences)*10, p=presences)
points(bg_dat, pch=19, cex=0.2, col=&#39;red&#39;)
points(presences, pch=19, cex=0.5)</code></pre>
<p><img src="5_pseudoabsence_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>Last, we need to join the presences and background data, and extract the environmental data.</p>
<pre class="r"><code># First, we prepare the presences data to contain a column indicating 1 for presence.
sp_env &lt;- data.frame(gbif_shrew2, occ=1)

# Second, we make sure the background data have the same columns, and indicate 0 for absence.
bg_dat &lt;- data.frame(bg_dat)
summary(bg_dat)</code></pre>
<pre><code>##        x                y        
##  Min.   : 3.083   Min.   :43.08  
##  1st Qu.: 9.250   1st Qu.:46.58  
##  Median :13.750   Median :48.58  
##  Mean   :14.292   Mean   :48.77  
##  3rd Qu.:19.750   3rd Qu.:50.75  
##  Max.   :26.750   Max.   :55.58</code></pre>
<pre class="r"><code>names(bg_dat) &lt;- c(&#39;decimalLongitude&#39;,&#39;decimalLatitude&#39;)
bg_dat$occ &lt;- 0
summary(bg_dat)</code></pre>
<pre><code>##  decimalLongitude decimalLatitude      occ   
##  Min.   : 3.083   Min.   :43.08   Min.   :0  
##  1st Qu.: 9.250   1st Qu.:46.58   1st Qu.:0  
##  Median :13.750   Median :48.58   Median :0  
##  Mean   :14.292   Mean   :48.77   Mean   :0  
##  3rd Qu.:19.750   3rd Qu.:50.75   3rd Qu.:0  
##  Max.   :26.750   Max.   :55.58   Max.   :0</code></pre>
<pre class="r"><code># Third, we bind these two data sets
sp_env &lt;- rbind(sp_env, bg_dat)
summary(sp_env)</code></pre>
<pre><code>##  decimalLongitude decimalLatitude      occ         
##  Min.   : 3.083   Min.   :43.08   Min.   :0.00000  
##  1st Qu.: 9.083   1st Qu.:46.42   1st Qu.:0.00000  
##  Median :13.150   Median :48.25   Median :0.00000  
##  Mean   :14.037   Mean   :48.61   Mean   :0.09091  
##  3rd Qu.:19.250   3rd Qu.:50.58   3rd Qu.:0.00000  
##  Max.   :26.750   Max.   :55.58   Max.   :1.00000</code></pre>
<pre class="r"><code># Last, we join this combined data set with the climate data.
sp_env &lt;- cbind(sp_env, raster::extract(x = clim, y = sp_env[,c(&#39;decimalLongitude&#39;,&#39;decimalLatitude&#39;)], cellnumbers=T) )
summary(sp_env)</code></pre>
<pre><code>##  decimalLongitude decimalLatitude      occ              cells      
##  Min.   : 3.083   Min.   :43.08   Min.   :0.00000   Min.   :35779  
##  1st Qu.: 9.083   1st Qu.:46.42   1st Qu.:0.00000   1st Qu.:46019  
##  Median :13.150   Median :48.25   Median :0.00000   Median :50714  
##  Mean   :14.037   Mean   :48.61   Mean   :0.09091   Mean   :50027  
##  3rd Qu.:19.250   3rd Qu.:50.58   3rd Qu.:0.00000   3rd Qu.:54492  
##  Max.   :26.750   Max.   :55.58   Max.   :1.00000   Max.   :61389  
##       bio1            bio2             bio3            bio4     
##  Min.   :-26.0   Min.   : 53.00   Min.   :24.00   Min.   :5092  
##  1st Qu.: 67.0   1st Qu.: 81.00   1st Qu.:29.00   1st Qu.:6260  
##  Median : 80.0   Median : 86.00   Median :31.00   Median :6822  
##  Mean   : 79.6   Mean   : 85.67   Mean   :30.34   Mean   :6899  
##  3rd Qu.: 94.0   3rd Qu.: 92.00   3rd Qu.:32.00   3rd Qu.:7559  
##  Max.   :164.0   Max.   :107.00   Max.   :39.00   Max.   :8884  
##       bio5            bio6              bio7            bio8      
##  Min.   : 78.0   Min.   :-126.00   Min.   :198.0   Min.   :-72.0  
##  1st Qu.:217.0   1st Qu.: -77.00   1st Qu.:257.0   1st Qu.:134.0  
##  Median :229.0   Median : -52.00   Median :279.0   Median :162.0  
##  Mean   :227.8   Mean   : -50.93   Mean   :278.7   Mean   :142.4  
##  3rd Qu.:243.0   3rd Qu.: -28.00   3rd Qu.:303.0   3rd Qu.:171.0  
##  Max.   :302.0   Max.   :  58.00   Max.   :331.0   Max.   :204.0  
##       bio9            bio10         bio11            bio12       
##  Min.   :-87.00   Min.   : 40   Min.   :-89.00   Min.   : 492.0  
##  1st Qu.:-18.00   1st Qu.:158   1st Qu.:-34.00   1st Qu.: 637.0  
##  Median :  9.00   Median :168   Median :-10.00   Median : 768.0  
##  Mean   : 21.32   Mean   :166   Mean   :-10.96   Mean   : 837.8  
##  3rd Qu.: 39.00   3rd Qu.:179   3rd Qu.:  6.00   3rd Qu.: 972.0  
##  Max.   :239.00   Max.   :239   Max.   : 95.00   Max.   :2121.0  
##      bio13           bio14            bio15           bio16      
##  Min.   : 60.0   Min.   : 11.00   Min.   : 7.00   Min.   :167.0  
##  1st Qu.: 80.0   1st Qu.: 31.00   1st Qu.:18.00   1st Qu.:223.0  
##  Median : 91.0   Median : 43.00   Median :27.00   Median :255.0  
##  Mean   :100.6   Mean   : 46.66   Mean   :25.98   Mean   :281.3  
##  3rd Qu.:117.0   3rd Qu.: 56.00   3rd Qu.:33.00   3rd Qu.:325.0  
##  Max.   :200.0   Max.   :153.00   Max.   :48.00   Max.   :580.0  
##      bio17           bio18         bio19      
##  Min.   : 65.0   Min.   : 78   Min.   : 65.0  
##  1st Qu.:104.0   1st Qu.:214   1st Qu.:114.0  
##  Median :139.0   Median :238   Median :155.0  
##  Mean   :152.8   Mean   :264   Mean   :171.5  
##  3rd Qu.:181.0   3rd Qu.:297   3rd Qu.:209.0  
##  Max.   :474.0   Max.   :563   Max.   :541.0</code></pre>
<div id="spatial-thinning" class="section level2">
<h2><span class="header-section-number">4.1</span> Spatial thinning</h2>
<p>When we prepare our distribution data for species distribution modelling, we also need to think about spatial autocorrelation. Using adjacent cells in model building can lead to problems with spatial autocorrelation. One way to avoid this is spatially thinning the records, for example using the package <code>spThin</code> <span class="citation">(Aiello-Lammens et al. 2015)</span>. Load the package and look up the help page <code>?thin</code>.</p>
<pre class="r"><code>library(spThin)

# The spThin package requires longitude/latitude coordinates, which we already have.
# Look up the help page and try to understand the function:
?thin

# thin() expects that the data.frame contains a column with the species name
sp_env$sp &lt;- &#39;Sorex_alpinus&#39;
  
# Remove adjacent cells of presence/background data:
xy &lt;- thin(sp_env, lat.col=&#39;decimalLatitude&#39;,long.col=&#39;decimalLongitude&#39;,spec.col=&#39;sp&#39;, thin.par=20,reps=5, write.files=F,locs.thinned.list.return=T)</code></pre>
<pre><code>## ********************************************** 
##  Beginning Spatial Thinning.
##  Script Started at: Sun Feb 21 18:27:12 2021
## lat.long.thin.count
## 1061 1063 1066 
##    1    1    3 
## [1] &quot;Maximum number of records after thinning: 1066&quot;
## [1] &quot;Number of data.frames with max records: 3&quot;
## [1] &quot;No files written for this run.&quot;</code></pre>
<pre class="r"><code>xy_keep &lt;- xy[[which.max(sapply(xy,nrow))]]

# Which run yields the most presence records?
which.max(sapply(xy,nrow))</code></pre>
<pre><code>## [1] 1</code></pre>
<pre class="r"><code># Thin the dataset - here, we first extract the cell numbers for the thinned coordinates and then use these to subset our data frame.
cells_thinned &lt;- cellFromXY(clim, xy_keep)
sp_thinned &lt;- sp_env[sp_env$cells %in% cells_thinned,]

# Plot the map and data
plot(mask, col=&#39;grey90&#39;, legend=F)
points(sp_thinned[,1:2],pch=19,col=c(&#39;black&#39;,&#39;red&#39;)[as.factor(sp_thinned$occ)], cex=0.3)</code></pre>
<p><img src="5_pseudoabsence_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<pre class="r"><code># Alternatively, remove adjacent cells separately in presence data and background data:
xy_pres &lt;- thin(sp_env[sp_env$occ==1,], lat.col=&#39;decimalLatitude&#39;,long.col=&#39;decimalLongitude&#39;,spec.col=&#39;sp&#39;, thin.par=20,reps=5, write.files=F,locs.thinned.list.return=T)</code></pre>
<pre><code>## ********************************************** 
##  Beginning Spatial Thinning.
##  Script Started at: Sun Feb 21 18:27:21 2021
## lat.long.thin.count
## 91 93 
##  1  4 
## [1] &quot;Maximum number of records after thinning: 93&quot;
## [1] &quot;Number of data.frames with max records: 4&quot;
## [1] &quot;No files written for this run.&quot;</code></pre>
<pre class="r"><code>xy_pres_keep &lt;- xy_pres[[which.max(sapply(xy_pres,nrow))]]

xy_abs &lt;- thin(sp_env[sp_env$occ==0,], lat.col=&#39;decimalLatitude&#39;,long.col=&#39;decimalLongitude&#39;,spec.col=&#39;sp&#39;, thin.par=20,reps=5, write.files=F,locs.thinned.list.return=T)</code></pre>
<pre><code>## ********************************************** 
##  Beginning Spatial Thinning.
##  Script Started at: Sun Feb 21 18:27:21 2021
## lat.long.thin.count
## 1012 1015 1016 1017 1020 
##    1    1    1    1    1 
## [1] &quot;Maximum number of records after thinning: 1020&quot;
## [1] &quot;Number of data.frames with max records: 1&quot;
## [1] &quot;No files written for this run.&quot;</code></pre>
<pre class="r"><code>xy_abs_keep &lt;- xy_abs[[which.max(sapply(xy_abs,nrow))]]

# Thin the dataset - here, we first extract the cell numbers for the thinned coordinates and then use these to subset our data frame.
cells_thinned2 &lt;- cellFromXY(clim, rbind(xy_pres_keep, xy_abs_keep))
sp_thinned2 &lt;- sp_env[sp_env$cells %in% cells_thinned2,]

# Plot the map and data
plot(mask, col=&#39;grey90&#39;, legend=F)
points(sp_thinned2[,1:2],pch=19,col=c(&#39;black&#39;,&#39;red&#39;)[as.factor(sp_thinned2$occ)], cex=0.3)</code></pre>
<p><img src="5_pseudoabsence_files/figure-html/unnamed-chunk-16-2.png" width="672" /></p>
<p><strong>Hint:</strong> Another useful function for spatial thinning is <code>gridSample()</code> in the <code>dismo</code> package.</p>
<div class="alert alert-info">
<p><em><strong>Exercise:</strong></em></p>
<p>Use the GBIF data for your own species (from practical 1), sample background data and prepare a data set with species and climate data. Use these data to run SDMs.</p>
</div>
</div>
</div>
<div id="references" class="section level1 unnumbered">
<h1>References</h1>
<div id="refs" class="references">
<div id="ref-Aiello-Lammens2015">
<p>Aiello-Lammens, Matthew E., Robert A. Boria, Aleksandar Radosavljevic, Bruno Vilela, and Robert P. Anderson. 2015. “spThin: An R Package for Spatial Thinning of Species Occurrence Records for Use in Ecological Niche Models.” <em>Ecography</em> 38 (5). Wiley: 541–45. <a href="https://doi.org/10.1111/ecog.01132">https://doi.org/10.1111/ecog.01132</a>.</p>
</div>
<div id="ref-BarbetMassin2012a">
<p>Barbet-Massin, Morgane, Frederic Jiguet, Cecile Helene Albert, and Wilfried Thuiller. 2012. “Selecting Pseudo-Absences for Species Distribution Models: How, Where and How Many?” <em>Methods in Ecology and Evolution</em> 3 (2): 327–38. <a href="https://doi.org/10.1111/j.2041-210X.2011.00172.x">https://doi.org/10.1111/j.2041-210X.2011.00172.x</a>.</p>
</div>
<div id="ref-Kramer-Schadt2013">
<p>Kramer-Schadt, Stephanie, Juergen Niedballa, John D. Pilgrim, Boris Schroeder, Jana Lindenborn, Vanessa Reinfelder, Milena Stillfried, et al. 2013. “The Importance of Correcting for Sampling Bias in Maxent Species Distribution Models.” <em>Diversity and Distributions</em> 19 (11): 1366–79. <a href="https://doi.org/10.1111/ddi.12096">https://doi.org/10.1111/ddi.12096</a>.</p>
</div>
<div id="ref-Phillips2009">
<p>Phillips, Steven J., Miroslav Dudik, Jane Elith, Catherine H. Graham, Anthony Lehmann, John Leathwick, and Simon Ferrier. 2009. “Sample Selection Bias and Presence-Only Distribution Models: Implications for Background and Pseudo-Absence Data.” <em>Ecological Applications</em> 19 (1): 181–97. <a href="https://doi.org/10.1890/07-2153.1">https://doi.org/10.1890/07-2153.1</a>.</p>
</div>
</div>
</div>

<!DOCTYPE html>
<html>

<br>
<hr />
<div id="footer">
<p>Damaris Zurell, 2020 <a href="http://creativecommons.org/licenses/by/4.0/" >(CC BY 4.0)</a>.  </p>
</div>

</html>


</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
